NewspaperAgency/urls.py
from django.contrib import admin
from django.urls import path, include

from NewspaperAgency import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("agency.urls", namespace="agency")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agency/urls.py
from django.urls import path
from agency.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    toggle_assign_to_newspaper,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorDeleteView,
    RedactorExperienceUpdateView,
)


urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"
    ),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path(
        "newspapers/<int:pk>/toggle-assign/",
        toggle_assign_to_newspaper,
        name="toggle-newspaper-assign",
    ),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path("redactors/create/", RedactorCreateView.as_view(), name="redactor-create"),
    path(
        "redactors/<int:pk>/update/",
        RedactorExperienceUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
]

app_name = "agency"

agency/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ["username"]
        verbose_name = "redactor"
        verbose_name_plural = "redactors"

    def get_absolute_url(self):
        return reverse("agency:redactor-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    context = models.TextField(max_length=255, blank=True)
    published_date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    redactors = models.ManyToManyField(Redactor, related_name="newspapers")

    def __str__(self):
        return self.title

agency/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from agency.models import Newspaper, Redactor


class NewspaperForm(forms.ModelForm):
    redactors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username..."}),
    )


class RedactorYearsOfExperienceUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = ["years_of_experience"]

    def clean_years_of_experience(self):
        return self.cleaned_data["years_of_experience"]


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title..."}),
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."}),
    )

agency/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import DetailView, DeleteView

from .models import Redactor, Newspaper, Topic
from .forms import (
    TopicSearchForm,
    NewspaperSearchForm,
    NewspaperForm,
    RedactorSearchForm,
    RedactorCreationForm,
    RedactorYearsOfExperienceUpdateForm,
)


@login_required
def index(request):
    """View function for the home page of the site."""

    num_redactors = Redactor.objects.count()
    num_newspapers = Newspaper.objects.count()
    num_topics = Topic.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_redactors": num_redactors,
        "num_newspapers": num_newspapers,
        "num_topics": num_topics,
        "num_visits": num_visits + 1,
    }

    return render(request, "agency/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    context_object_name = "topic_list"
    template_name = "agency/topic_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TopicSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Topic.objects.all()
        form = TopicSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("agency:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("agency:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("agency:topic-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5
    queryset = Newspaper.objects.all().select_related("topic")
    template_name = "agency/newspaper_list.html"
    context_object_name = "newspaper_list"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = NewspaperSearchForm(initial={"title": title})
        return context

    def get_queryset(self):
        form = NewspaperSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(title__icontains=form.cleaned_data["title"])

        return self.queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("agency:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("agency:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("agency:newspaper-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = RedactorSearchForm(initial={"username": username})

        return context

    def get_queryset(self):
        queryset = Redactor.objects.all()
        form = RedactorSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(username__icontains=form.cleaned_data["username"])

        return queryset


class RedactorDetailView(LoginRequiredMixin, DetailView):
    model = Redactor


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm


class RedactorDeleteView(LoginRequiredMixin, DeleteView):
    model = Redactor
    success_url = reverse_lazy("agency:redactor-list")


class RedactorExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorYearsOfExperienceUpdateForm
    success_url = reverse_lazy("agency:redactor-list")


@login_required
def toggle_assign_to_newspaper(request, pk):
    redactor = Redactor.objects.get(id=request.user.id)
    if (
        Newspaper.objects.get(id=pk) in redactor.newspapers.all()
    ):  # probably could check if car exists
        redactor.newspapers.remove(pk)
    else:
        redactor.newspapers.add(pk)
    return HttpResponseRedirect(reverse_lazy("agency:newspaper-detail", args=[pk]))

templates/agency/index.html
{% extends "base-fullscreen.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Newspaper agency</title>
</head>
<body class="presentation-page bg-gray-200">

  <header class="header-2">
    <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg10.jpg')">
      <span class="mask bg-gradient-primary opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">Newspaper agency</h1>
            <p class="lead text-white mt-3">Welcome!<br /></p>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
    <section class="pt-3 pb-4" id="count-stats">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 mx-auto py-3">
            <div class="row">
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-primary"><span id="state1" countTo="{{ num_redactors }}">0</span>+</h1>
                  <h5 class="mt-3">Redactors</h5>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-primary"><span id="state2" countTo="{{ num_newspapers }}">0</span>+</h1>
                  <h5 class="mt-3">Newspapers</h5>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center">
                  <h1 class="text-primary" id="state3" countTo="{{ num_topics }}">0</h1>
                  <h5 class="mt-3">Topics</h5>
                </div>
                <hr class="vertical dark">
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

  <!--   Core JS Files   -->
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>
  <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY"></script>
  <script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>
</body>
</html>
{% endblock %}

templates/agency/newspaper_confirm_delete.html
{% extends "base-fullscreen.html" %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card mt-4">
          <div class="card-body text-center">
            <h1 class="card-title">Delete newspaper?</h1>
            <p class="card-text">{{ newspaper.title }}</p>
            <form action="" method="post">
              {% csrf_token %}
              <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary">Delete</button>
                <a class="btn btn-success" href="{% url 'agency:newspaper-list' %}">Cancel</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/agency/newspaper_detail.html
{% extends "base-fullscreen.html" %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card mt-4">
          <div class="card-header bg-primary text-white">
            <h1 class="card-title text-white">{{ newspaper.title }}</h1>
          </div>
          <div class="card-body">
            <p><strong>Topic:</strong> {{ newspaper.topic }}</p>
            <p><strong>Context:</strong> {{ newspaper.context }}</p>
          </div>
          <div class="card-footer">
            <a href="{% url 'agency:newspaper-delete' pk=newspaper.pk %}" class="btn btn-danger mr-2">
              Delete
            </a>
            <a href="{% url 'agency:newspaper-update' pk=newspaper.pk %}" class="btn btn-success">
              Update
            </a>
          </div>
        </div>
        <div class="card mt-4">
          <div class="card-header bg-primary text-white">
            <h4 class="card-title text-white">Redactors</h4>
          </div>
          <div class="card-body">
            {% if newspaper in user.newspapers.all %}
              <a href="{% url 'agency:toggle-newspaper-assign' pk=newspaper.id %}" class="btn btn-danger mb-3">
                Delete me from this newspaper
              </a>
            {% else %}
              <a href="{% url 'agency:toggle-newspaper-assign' pk=newspaper.id %}" class="btn btn-success mb-3">
                Assign me to this newspaper
              </a>
            {% endif %}
            <hr>
            <ul>
              {% for redactor in newspaper.redactors.all %}
                <li>{{ redactor.username }} ({{ redactor.first_name }} {{ redactor.last_name }})</li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/agency/newspaper_form.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block styles %}
<style>
.search-line {
  display: flex;
  align-items: center;
  background-color: white;
  border: 2px solid #000;
  border-radius: 5px;
  padding: 2px;
  width: 300px;
  flex-shrink: 0;
}

.search-line input[type="text"] {
  border: 1px solid #000;
  background-color: transparent;
  outline: none;
  padding: 2px;
  color: black;
  font-size: 14px;
  flex-grow: 1;
}
</style>
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card mt-4">
          <div class="card-body text-center">
            <h1>{{ object|yesno:"Update,Create" }} newspaper</h1>
            <form action="" method="post" novalidate>
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group">
                  {{ field|as_crispy_field }}
                </div>
              {% endfor %}
            <br>
              <div class="d-flex justify-content-center">
                <input type="submit" value="Submit" class="btn btn-primary">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/agency/newspaper_list.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1 class="list-group-item bg-primary rounded d-flex align-items-center">
          <span class="flex-grow-1 text-light">Newspaper List {% include "includes/search_line.html" %}</span>
          <a href="{% url 'agency:newspaper-create' %}" class="btn btn-white link-to-page ml-auto" style="width: 20%;">Create</a>
        </h1>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-12">
        {% if newspaper_list %}
          <table class="table table-striped table-bordered">
            <thead class="table-primary">
              <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Topic</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              {% for newspaper in newspaper_list %}
                <tr>
                  <td><a href="{% url 'agency:newspaper-detail' pk=newspaper.id %}">{{ newspaper.id }}</a></td>
                  <td>{{ newspaper.title }}</td>
                  <td>{{ newspaper.topic }}</td>
                  <td>{{ newspaper.published_date }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <p>There are no newspapers in the agency.</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

templates/agency/redactor_confirm_delete.html
{% extends "base-fullscreen.html" %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card mt-4">
          <div class="card-body text-center">
            <h1 class="card-title">Delete Redactor?</h1>
            <p class="card-text">{{ redactor.username }}</p>
            <form action="" method="post">
              {% csrf_token %}
              <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary">Delete</button>
                <a class="btn btn-success" href="{% url 'agency:redactor-list' %}">Cancel</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/agency/redactor_detail.html
{% extends "base-fullscreen.html" %}

{% block content %}

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="row">
          <div class="col-md-6">
            <div class="card mt-4">
              <div class="card-header bg-primary text-white">
                <h1 class="card-title text-white">Username: {{ redactor.username }}</h1>
              </div>
              <div class="card-body">
                <p><strong>First name:</strong> {{ redactor.first_name }}</p>
                <p><strong>Last name:</strong> {{ redactor.last_name }}</p>
                <p><strong>Years of experience:</strong> {{ redactor.years_of_experience }}</p>
                <p><strong>Is staff:</strong> {{ redactor.is_staff }}</p>
              </div>
              <div class="card-footer">
                <a href="{% url 'agency:redactor-delete' pk=redactor.id %}" class="btn btn-danger mr-2">
                  Delete
                </a>
                <a href="{% url 'agency:redactor-update' pk=redactor.pk %}" class="btn btn-success">
                  Update years of experience
                </a>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card mt-4">
              <div class="card-header bg-primary text-white">
                <h4 class="card-title text-white">Newspapers</h4>
              </div>
              <div class="card-body">
                {% for newspaper in redactor.newspapers.all %}
                  <div class="mb-3">
                    <p><strong>Title:</strong> {{ newspaper.title }}</p>
                    <p><strong>Topic:</strong> {{ newspaper.topic }}</p>
                    <p class="text-muted"><strong>Id:</strong> {{ newspaper.id }}</p>
                  </div>
                  <hr>
                {% empty %}
                  <p>No newspapers!</p>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/agency/redactor_form.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card mt-4">
          <div class="card-body text-center">
            <h1 class="card-title">{{ object|yesno:"Update,Create" }} redactor</h1>
            <form action="" method="post" novalidate>
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group">
                  {{ field|as_crispy_field }}
                </div>
              {% endfor %}
            <br>
              <div class="d-flex justify-content-center">
                <input type="submit" value="Submit" class="btn btn-primary">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/agency/redactor_list.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1 class="list-group-item bg-primary rounded d-flex align-items-center">
          <span class="flex-grow-1 text-light">Redactor List {% include "includes/search_line.html" %}</span>
          <a href="{% url 'agency:redactor-create' %}" class="btn btn-white link-to-page ml-auto" style="width: 20%;">Create</a>
        </h1>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-12">
        {% if redactor_list %}
          <table class="table table-striped table-bordered">
            <thead class="table-primary">
              <tr>
                <th>ID</th>
                <th>Username</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Years of experience</th>
              </tr>
            </thead>

            <tbody>
              {% for redactor in redactor_list %}
                <tr>
                  <td>{{ redactor.id }}</td>
                  <td><a href="{{ redactor.get_absolute_url }}">{{ redactor.username }} {% if user == redactor %} (Me){% endif %}</a></td>
                  <td>{{ redactor.first_name }}</td>
                  <td>{{ redactor.last_name }}</td>
                  <td>{{ redactor.years_of_experience }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <p>There are no redactors in the service.</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

templates/agency/topic_confirm_delete.html
{% extends "base-fullscreen.html" %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card mt-4">
          <div class="card-body text-center">
            <h1 class="card-title">Delete Topic?</h1>
            <p class="card-text">{{ topic.name }}</p>
            <form action="" method="post">
              {% csrf_token %}
              <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary">Delete</button>
                <a class="btn btn-success" href="{% url 'agency:topic-list' %}">Cancel</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/agency/topic_form.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card mt-4">
          <div class="card-body text-center">
            <h1 class="card-title">{{ object|yesno:"Update,Create" }} topic</h1>
            <form action="" method="post" novalidate>
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group">
                  {{ field|as_crispy_field }}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-center">
                <input type="submit" value="Submit" class="btn btn-primary">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/agency/topic_list.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1 class="list-group-item bg-primary rounded d-flex align-items-center">
          <span class="flex-grow-1 text-light">Topic List {% include "includes/search_line.html" %}</span>
          <a href="{% url 'agency:topic-create' %}" class="btn btn-white link-to-page ml-auto" style="width: 20%;">Create</a>
        </h1>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-12">
        {% if topic_list %}
          <table class="table table-striped table-bordered">
            <thead class="table-primary">
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Update</th>
                <th>Delete</th>
              </tr>
            </thead>

            <tbody>
              {% for topic in topic_list %}
                <tr>
                  <td>{{ topic.id }}</td>
                  <td>{{ topic.name }}</td>
                  <td>
                    <a class="text-success" href="{% url 'agency:topic-update' pk=topic.id %}">Update</a>
                  </td>
                  <td>
                    <a class="text-danger" href="{% url 'agency:topic-delete' pk=topic.id %}">Delete</a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <p>There are no topics in the service.</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}