NewspaperAgency/urls.py
from django.contrib import admin
from django.urls import path, include

from NewspaperAgency import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("agency.urls", namespace="agency")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agency/urls.py
from django.urls import path
from agency.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    toggle_assign_to_newspaper,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorDeleteView,
    RedactorExperienceUpdateView,
)


urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"
    ),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path(
        "newspapers/<int:pk>/toggle-assign/",
        toggle_assign_to_newspaper,
        name="toggle-newspaper-assign",
    ),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path("redactors/create/", RedactorCreateView.as_view(), name="redactor-create"),
    path(
        "redactors/<int:pk>/update/",
        RedactorExperienceUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
]

app_name = "agency"

templates/includes/footer.html
  <footer class="footer pt-5 mt-5">
    <div class="container">
      <div class=" row">
        <div class="col-md-3 mb-4 ms-auto">
          <div>
            <a href="https://appseed.us/product/django-material-kit">
              <img src="{{ ASSETS_ROOT }}/img/logo-ct-dark.png" class="mb-3 footer-logo" alt="main_logo">
            </a>
            <h6 class="font-weight-bolder mb-4">Material Kit 2</h6>
          </div>
          <div>
            <ul class="d-flex flex-row ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://www.facebook.com/CreativeTim" target="_blank">
                  <i class="fab fa-facebook text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://twitter.com/creativetim" target="_blank">
                  <i class="fab fa-twitter text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://dribbble.com/creativetim" target="_blank">
                  <i class="fab fa-dribbble text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://github.com/creativetimofficial" target="_blank">
                  <i class="fab fa-github text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://www.youtube.com/channel/UCVyTG4sCw-rOvB9oHkzZD1w" target="_blank">
                  <i class="fab fa-youtube text-lg opacity-8"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-sm">Company</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/presentation" target="_blank">
                  About Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/templates/free" target="_blank">
                  Freebies
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/templates/premium" target="_blank">
                  Premium Tools
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/blog" target="_blank">
                  Blog
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-sm">Resources</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://iradesign.io/" target="_blank">
                  Illustrations
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/bits" target="_blank">
                  Bits & Snippets
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/affiliates/new" target="_blank">
                  Affiliate Program
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-sm">Help & Support</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/contact-us" target="_blank">
                  Contact Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/knowledge-center" target="_blank">
                  Knowledge Center
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://services.creative-tim.com/?ref=ct-mk2-footer" target="_blank">
                  Custom Development
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/sponsorships" target="_blank">
                  Sponsorships
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
          <div>
            <h6 class="text-sm">Legal</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/knowledge-center/terms-of-service" target="_blank">
                  Terms & Conditions
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/knowledge-center/privacy-policy" target="_blank">
                  Privacy Policy
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/license" target="_blank">
                  Licenses (EULA)
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-12">
          <div class="text-center">
            <p class="text-dark my-4 text-sm font-weight-normal">
              &copy; <a href="https://bit.ly/3fKQZaL" class="font-weight-bold" target="_blank">Creative Tim</a>
              coded by <a href="https://appseed.us" class="font-weight-bold" target="_blank">AppSeed</a>.
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/navigation.html
<style>
  .sidebar-nav {
    margin-top: 1em; /* Додайте потрібний відступ у пікселях */
  }
</style>


<ul class="sidebar-nav list-group">
  {% if request.user.is_authenticated %}
    <li class="list-group-item bg-primary text-light">User: <a href="{{ user.get_absolute_url }}" class="text-light">{{ user.get_username }}</a></li>
  {% endif %}
  <li class="list-group-item sidebar-title">
    <a href="/" class="nav-link">
      <i class="material-icons opacity-6 me-2 text-md">home</i>
      Home
    </a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'agency:redactor-list' %}" class="nav-link">
      <i class="material-icons opacity-6 me-2 text-md">people</i>
      All Redactors
    </a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'agency:newspaper-list' %}" class="nav-link">
      <i class="material-icons opacity-6 me-2 text-md">article</i>
      All Newspapers
    </a>
  </li>
  <li class="list-group-item dropdown">
    <a href="{% url 'agency:topic-list' %}" class="nav-link">
      <i class="material-icons opacity-6 me-2 text-md">subject</i>
      All topics
    </a>
  </li>

  {% if request.user.is_authenticated %}
    <li class="list-group-item">
      <a href="{% url 'logout' %}" class="nav-link">
        <i class="fa fa-sign-out me-1"></i>
        <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign OUT">Logout</p>
      </a>
    </li>
  {% endif %}
</ul>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <div class="d-flex justify-content-center">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?{% query_transform request page=previous_obj.next_page_number %}" class="page-link" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
      {% endif %}

      {% for page in paginator.page_range %}
        {% if page_obj.number == page %}
          <li class="page-item active">
            <span class="page-link">{{ page }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a href="?{% query_transform request page=page %}" class="page-link">{{ page }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
{% endif %}

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>

templates/includes/search_line.html
{% load crispy_forms_filters %}

<style>

  .search-button {
    margin-left: 5px;
    height: 100%;
  }

  .search-wrapper {
    display: flex;
    align-items: center;
    justify-content: space-between;
    height: 100%;
  }
</style>

<form action="" method="get" class="form-inline">
  <div class="input-group">
    <div class="search-wrapper">
      <div class="input-group search-line">
        {{ search_form|crispy }}
      </div>
      <button type="submit" class="btn btn-primary bg-white search-button">
        <i class="fas fa-search text-primary"></i>
      </button>
    </div>
  </div>
</form>